### PR TITLE
1.1

### PR DESCRIPTION
**Pull request by Azyyyyyy**
Adds CanScan, Scanning and try methods for start and stop tasks and commenting

(Yes I didn't realize the email wasn't what it should be so it shows as aaron1001 xD)

### CODE REVIEW

**Review by Perksey — APPROVED** [review]
Awesome stuff Aaron, this gets my green light. But before I merge, can you ensure that all `csproj`s or `AssemblyInfo`s have 1.1.0 set as their version? I see you've already done the main project.

**Comment by Azyyyyyy** [comment]
There you go, can't seem to find a way to up the Ultz.XNFC.Android package tho

**Comment by Perksey** [comment]
https://github.com/AzyIsCool/XNFC/blob/master/src/Ultz.XNFC.Android/Properties/AssemblyInfo.cs

**Comment by Azyyyyyy** [comment]
Done

**Review by Perksey — APPROVED** [review]

**Pull request merged**
